server:
  context-path: /micro
  port: 8080
spring:
  cloudant:
    username: ${vcap.services.lightblue-cloudant.credentials.username:c7f097a9-1b39-44b2-b79b-2ae6e8be8140-bluemix}
    password: ${vcap.services.lightblue-cloudant.credentials.password:4851f59a188ee6494c427d1f6fc8d767270bd65bc487b752d70315f021f2ac44}
    host: ${vcap.services.lightblue-cloudant.credentials.host:c7f097a9-1b39-44b2-b79b-2ae6e8be8140-bluemix.cloudant.com}
    protocol: https
    port: 443
    database: customers
services:
 - lightblue-cloudant